# Generated by Django 3.0.2 on 2020-08-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200617_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='education_level',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
