# Generated by Django 3.0.8 on 2020-09-11 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_auto_20200829_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('head', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accountuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.CreateModel(
            name='NoticeBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('statement', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isFaceBanner', models.BooleanField(default=True)),
                ('written_date', models.DateTimeField()),
                ('published_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('valid_till_date', models.DateTimeField()),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.AccountUser')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('summary', models.CharField(blank=True, max_length=100, null=True)),
                ('paragraph', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isHomeArticle', models.BooleanField(default=True)),
                ('written_date', models.DateTimeField()),
                ('published_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccountUser')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
            ],
        ),
    ]
