# Generated by Django 3.0.8 on 2020-09-11 21:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200911_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='country',
            name='longi',
        ),
        migrations.RemoveField(
            model_name='userclass',
            name='user_group',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Country'),
        ),
        migrations.AddField(
            model_name='country',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/countries/flags'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserClass'),
        ),
    ]
