# Generated by Django 3.0.8 on 2020-09-11 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200911_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.AccountUser'),
        ),
    ]
