# Generated by Django 3.0.8 on 2020-09-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200911_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(blank=True, max_length=50, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('statement', models.TextField(blank=True, null=True)),
                ('statement2', models.TextField(blank=True, null=True)),
                ('statement3', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isFaceBanner', models.BooleanField(default=True)),
                ('written_date', models.DateTimeField()),
                ('published_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
            ],
        ),
    ]
