# Generated by Django 3.0.8 on 2020-11-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_about_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
