# Generated by Django 3.0.8 on 2020-11-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201117_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='about_us',
            name='isFaceBanner',
            field=models.BooleanField(default=False),
        ),
    ]
