# Generated by Django 3.0.8 on 2020-11-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_auto_20201109_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shippig_cost',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
