# Generated by Django 3.0.8 on 2020-11-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_order_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='second_image',
        ),
        migrations.AddField(
            model_name='product',
            name='first_image',
            field=models.ImageField(blank=True, upload_to='products_images/'),
        ),
    ]
