# Generated by Django 3.0.8 on 2020-11-21 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0008_auto_20201121_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection_Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('isActive', models.BooleanField(default=True)),
                ('isFaceBanner', models.BooleanField(default=True)),
                ('written_date', models.DateTimeField()),
                ('published_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce_app.Product')),
            ],
        ),
    ]
