# Generated by Django 3.0.8 on 2020-11-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0012_auto_20201124_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('unattended', 'unattended'), ('waiting_payment', 'High'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('recieved', 'recieved'), ('in_transit', 'in_transit')], default='unattended', max_length=20, null=True),
        ),
    ]
