# Generated by Django 3.0.8 on 2020-11-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0014_paynowpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenuAds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('category', models.CharField(blank=True, choices=[('just_in', 'just_in'), ('summer_look', 'summer_look'), ('lovers_show_off', 'lovers_show_off'), ('ambitious_personalities', 'ambitious_personalities'), ('ambitious_kidz', 'ambitious_kidz'), ('fashion_blog', 'fashion_blog')], default='just_in', max_length=50, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='major_colors',
            field=models.ManyToManyField(blank=True, to='ecommerce_app.ProductMaterialMainColor'),
        ),
    ]
