# Generated by Django 3.0.8 on 2020-11-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0017_product_collecion_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=70, null=True)),
                ('nav_tag', models.CharField(blank=True, max_length=70, null=True)),
                ('collecion_category', models.CharField(blank=True, choices=[('just_in', 'just_in'), ('summer_look', 'summer_look'), ('lovers_show_off', 'lovers_show_off'), ('ambitious_personalities', 'ambitious_personalities'), ('ambitious_kidz', 'ambitious_kidz'), ('fashion_blog', 'fashion_blog')], default='just_in', max_length=50, null=True)),
            ],
        ),
    ]
