# Generated by Django 3.0.8 on 2020-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0018_menuitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
