countries_choices = {
'Algeria':'Algeria',
'Angola':'Angola',
'Benin':'Benin',
'Botswana':'Botswana',
'Burkina_Faso':'Burkina_Faso',
'Burundi':'Burundi',
'Cameroon':'Cameroon',
'Cape_Verde':'Cape-Verde',
'Central_African_Republic':'Central-African-Republic',
'Chad':'Chad',
'Camoros':'Camoros',
'DRC':'Democratic-Republic-of-the-Congo',
'Djibouti':'Djibouti',
'Egypt':'Egypt',
'Equatorial-Guinea':'Equatorial-Guinea',
'Eritrea':'Eritrea',
'Ethiopia':'Ethiopia',
'Gabon':'Gabon',
'Gambia':'Gambia',
'Ghana':'Ghana',
'Guinea':'Guinea',
'Guinea-Bissau':'Guinea-Bissau',
'Ivory_Coast':'Ivory-Coast',
'Kenya':'Kenya',
'Lesotho':'Lesotho',
'Liberia':'Liberia',
'Libya':'Libya',
'Madagascar':'Madagascar',
'Malawi':'Malawi',
'Mali':'Mali',
'Mauritania':'Mauritania',
'Mauritius':'Mauritius',
'Morocco':'Morocco',
'Mozambique':'Mozambique',
'Namibia':'Namibia',
'Niger':'Niger',
'Nigeria':'Nigeria',
'Rwanda':'Rwanda',
'Sao_Tome_and_Principe':'Sao-Tome-and-Principe',
'Senegal':'Senegal',
'Seychelles':'Seychelles',
'Sierra_Leone':'Sierra-Leone',
'Somalia':'Somalia',
'South_Africa':'South-Africa',
'South_Sudan':'South-Sudan',
'Sudan':'Sudan',
'Swaziland':'Swaziland',
'Tanzania':'Tanzania',
'Togo':'Togo',
'Tunisia':'Tunisia',
'Uganda':'Uganda',
'Zambia':'Zambia',
'Zimbabwe':'Zimbabwe',
}

role_choices = {
'farmer':'farmer',
'processor':'processor',
'investor':'investor',
'distributor':'distributor',
'marketer':'marketer',
}

state_choices = {
        'AK': 'Alaska',
}