# Generated by Django 3.0.8 on 2020-09-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_auto_20200911_2318'),
        ('mush_store', '0002_delete_authappshopuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=70, null=True)),
                ('long_name', models.CharField(blank=True, max_length=70, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('description', models.TextField(blank=True, null=True)),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=70, null=True)),
                ('long_name', models.CharField(blank=True, max_length=70, null=True)),
                ('major_color', models.CharField(blank=True, max_length=70, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('description', models.TextField(blank=True, null=True)),
                ('stock_date', models.DateTimeField()),
                ('restoke_date', models.DateTimeField()),
                ('isAvailable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=70, null=True)),
                ('long_name', models.CharField(blank=True, max_length=70, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('description', models.TextField(blank=True, null=True)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mush_store.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdverts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isFaceBanner', models.BooleanField(default=True)),
                ('written_date', models.DateTimeField()),
                ('published_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mush_store.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mush_store.SubCategory'),
        ),
        migrations.CreateModel(
            name='DepartmentAdverts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('statement', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isFaceBanner', models.BooleanField(default=True)),
                ('written_date', models.DateTimeField()),
                ('published_date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
            ],
        ),
    ]
