# Generated by Django 3.0.8 on 2020-09-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mush_store', '0004_auto_20200918_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentadverts',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mush_store.Product'),
        ),
    ]
