# Generated by Django 3.0.8 on 2020-09-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mush_store', '0006_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size1_model_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/models/products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='size2_model_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/models/products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='size3_model_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/models/products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='size4_model_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/models/products/%Y/%m/%d'),
        ),
    ]
