# Generated by Django 3.0.8 on 2020-09-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mush_store', '0007_auto_20200925_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_name',
            new_name='name',
        ),
    ]
