# Generated by Django 3.0.8 on 2020-09-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mush_store', '0008_auto_20200926_0821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='image',
        ),
    ]
