# Generated by Django 3.0.8 on 2020-10-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mush_store', '0009_auto_20200926_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentadverts',
            name='category',
        ),
        migrations.RemoveField(
            model_name='departmentadverts',
            name='dep',
        ),
        migrations.RemoveField(
            model_name='departmentadverts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='productadverts',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productadverts',
            name='product',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='main_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='DepartmentAdverts',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAdverts',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
